### ISSUE TITLE
Current plugin breaks OS 2.1

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/openslides-csv-export#33]
No matter if I use the master or development branch of this plugin, when I use it with the latest OS 2.1 development snapshot, I can then not login to OpenSlides after restarting its server.

After removing it from the plugins folder, I can use OS again.
If possible this plugin should work with OS 2.1 beta.

**Comment by emanuelschuetze** [comment]
2.0.1 works now with OpenSlides 2.1

**Comment by donovaly** [comment]
> 2.0.1 works now with OpenSlides 2.1

Not for me with OS 2.1 beta3. When pressing the Download button the the CSV export menu, I am referred this this URL:
http://localhost:8000/csv_export_lists_of_speakers/
An the content of the page is just "Server Error (500)"

**Comment by emanuelschuetze** [comment]
Thanks for testing. Fixed with #36.

**Comment by donovaly** [comment]
> Fixed with #36.

Many thanks. Could you make a new release or sent me a new version by private mail to test it?

**Comment by donovaly** [comment]
Ping

**Comment by emanuelschuetze** [comment]
Done: 
https://github.com/OpenSlides/openslides-csv-export/releases/tag/2.0.2

**Comment by donovaly** [comment]
Many thanks, it works.
