### ISSUE TITLE
openslides-csv-export doesn't work with OS 2.2

### ISSUE THREAD

**Issue by donovaly** [OpenSlides/openslides-csv-export#39]
In OS 2.1 one could extract the content of the ZIP file with the release to the subfolder ~/openslides/plugins of OS. Now there is no longer a folder called "plugins".

I played a bit but cannot find a way to install the openslides-csv-export plugin.

**Comment by FinnStutzenstein** [comment]
Are you working with a windows portable version or with linux and `pip install openslides`?

**Comment by emanuelschuetze** [comment]
Plugin works for me in latest master portable version.
@donovaly Can you verify it?

**Comment by emanuelschuetze** [comment]
Done, 2.0.3 released.
